/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Tue Jul 02 02:08:55 GMT 2024
 */

package com.alibaba.nacos.client.naming.remote.gprc.redo;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class NamingGrpcRedoService_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "com.alibaba.nacos.client.naming.remote.gprc.redo.NamingGrpcRedoService"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(NamingGrpcRedoService_ESTest_scaffolding.class.getClassLoader() ,
      "com.alibaba.nacos.client.naming.backups.FailoverReactor",
      "com.alibaba.nacos.common.notify.listener.Subscriber",
      "com.alibaba.nacos.client.auth.ram.injector.NamingResourceInjector",
      "com.alibaba.nacos.client.naming.remote.NamingClientProxy",
      "com.alibaba.nacos.common.http.HttpClientFactory",
      "com.alibaba.nacos.api.selector.AbstractSelector",
      "com.alibaba.nacos.client.naming.core.ServerListManager",
      "com.alibaba.nacos.common.http.client.handler.AbstractResponseHandler",
      "com.alibaba.nacos.client.naming.remote.AbstractNamingClientProxy",
      "com.alibaba.nacos.client.naming.remote.gprc.redo.RedoScheduledTask",
      "com.alibaba.nacos.common.model.RequestHttpEntity",
      "com.alibaba.nacos.common.utils.MapUtil",
      "com.alibaba.nacos.common.http.param.Query",
      "com.alibaba.nacos.client.auth.ram.RamClientAuthServiceImpl",
      "com.alibaba.nacos.client.auth.ram.injector.AbstractResourceInjector",
      "com.alibaba.nacos.api.naming.remote.request.InstanceRequest",
      "com.alibaba.nacos.common.remote.client.ServerRequestHandler",
      "com.alibaba.nacos.client.naming.remote.http.NamingHttpClientManager",
      "com.alibaba.nacos.common.remote.client.ConnectionEventListener",
      "com.alibaba.nacos.api.naming.pojo.ListView",
      "com.alibaba.nacos.common.utils.InternetAddressUtil",
      "com.alibaba.nacos.client.logging.NacosLogging$NacosLoggingInstance",
      "com.alibaba.nacos.client.naming.event.InstancesChangeEvent",
      "com.alibaba.nacos.common.http.Callback",
      "com.alibaba.nacos.api.exception.api.NacosApiException",
      "com.alibaba.nacos.api.common.Constants",
      "com.alibaba.nacos.client.env.AbstractPropertySource",
      "com.alibaba.nacos.common.utils.StringUtils",
      "com.alibaba.nacos.api.naming.remote.request.AbstractNamingRequest",
      "com.alibaba.nacos.common.http.HttpClientConfig$HttpClientConfigBuilder",
      "com.alibaba.nacos.api.exception.runtime.NacosLoadException",
      "com.alibaba.nacos.api.utils.StringUtils",
      "com.alibaba.nacos.plugin.auth.spi.client.ClientAuthService",
      "com.alibaba.nacos.api.naming.remote.request.ServiceListRequest",
      "com.alibaba.nacos.common.http.client.request.JdkHttpClientRequest",
      "com.alibaba.nacos.api.naming.remote.request.SubscribeServiceRequest",
      "com.alibaba.nacos.client.naming.backups.FailoverReactor$SwitchRefresher",
      "com.alibaba.nacos.common.utils.ConvertUtils",
      "com.alibaba.nacos.common.http.client.response.HttpClientResponse",
      "com.alibaba.nacos.common.utils.CollectionUtils",
      "com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy",
      "com.alibaba.nacos.client.env.NacosClientProperties",
      "com.alibaba.nacos.client.env.convert.BooleanConverter",
      "com.alibaba.nacos.client.security.SecurityProxy",
      "com.alibaba.nacos.client.logging.logback.LogbackNacosLogging",
      "com.alibaba.nacos.client.naming.backups.FailoverReactor$FailoverFileReader",
      "com.alibaba.nacos.api.naming.utils.NamingUtils",
      "com.alibaba.nacos.client.naming.backups.FailoverReactor$DiskFileWriter",
      "com.alibaba.nacos.common.task.AbstractExecuteTask",
      "com.alibaba.nacos.client.env.SourceType",
      "com.alibaba.nacos.client.logging.log4j2.Log4J2NacosLogging",
      "com.alibaba.nacos.client.naming.event.ServerListChangedEvent",
      "com.alibaba.nacos.client.naming.remote.gprc.redo.data.RedoData$RedoType",
      "com.alibaba.nacos.client.env.convert.LongConverter",
      "com.alibaba.nacos.client.naming.remote.gprc.redo.data.InstanceRedoData",
      "com.alibaba.nacos.common.http.client.handler.RestResultResponseHandler",
      "com.alibaba.nacos.client.env.PropertiesPropertySource",
      "com.alibaba.nacos.client.auth.ram.RamContext",
      "com.alibaba.nacos.common.lifecycle.Closeable",
      "com.alibaba.nacos.common.utils.PropertyUtils",
      "com.alibaba.nacos.api.naming.pojo.Service",
      "com.alibaba.nacos.api.remote.request.Request",
      "com.alibaba.nacos.common.remote.client.ServerListFactory",
      "com.alibaba.nacos.client.naming.remote.gprc.redo.data.SubscriberRedoData",
      "com.alibaba.nacos.client.logging.logback.NacosJoranConfigurator",
      "com.alibaba.nacos.common.utils.ThreadUtils",
      "com.alibaba.nacos.client.naming.remote.gprc.redo.data.RedoData",
      "com.alibaba.nacos.common.http.param.Header",
      "com.alibaba.nacos.client.auth.impl.NacosClientAuthServiceImpl",
      "com.alibaba.nacos.api.naming.pojo.Instance",
      "com.alibaba.nacos.common.http.client.handler.StringResponseHandler",
      "com.alibaba.nacos.client.utils.LogUtils",
      "com.alibaba.nacos.common.http.client.request.HttpClientRequest",
      "com.alibaba.nacos.client.naming.cache.ServiceInfoHolder",
      "com.alibaba.nacos.common.model.RestResult",
      "com.alibaba.nacos.common.http.client.handler.ResponseHandler",
      "com.alibaba.nacos.common.spi.NacosServiceLoader",
      "com.alibaba.nacos.api.remote.response.Response",
      "com.alibaba.nacos.client.env.convert.AbstractPropertyConverter",
      "com.alibaba.nacos.common.http.client.NacosRestTemplate",
      "com.alibaba.nacos.common.model.RestResult$ResResultBuilder",
      "com.alibaba.nacos.client.naming.remote.http.NamingHttpClientManager$NamingHttpClientFactory",
      "com.alibaba.nacos.api.remote.Payload",
      "com.alibaba.nacos.plugin.auth.spi.client.AbstractClientAuthService",
      "com.alibaba.nacos.client.naming.remote.gprc.redo.data.BatchInstanceRedoData",
      "com.alibaba.nacos.client.env.DefaultSettingPropertySource",
      "com.alibaba.nacos.client.logging.AbstractNacosLogging",
      "com.alibaba.nacos.client.logging.NacosLogging",
      "com.alibaba.nacos.common.notify.Event",
      "com.alibaba.nacos.common.http.client.NacosAsyncRestTemplate",
      "com.alibaba.nacos.common.task.NacosTask",
      "com.alibaba.nacos.common.http.client.AbstractNacosRestTemplate",
      "com.alibaba.nacos.common.tls.SelfHostnameVerifier",
      "com.alibaba.nacos.client.logging.logback.NacosClientPropertyAction",
      "com.alibaba.nacos.client.env.convert.IntegerConverter",
      "com.alibaba.nacos.plugin.auth.spi.client.ClientAuthPluginManager",
      "com.alibaba.nacos.common.http.AbstractHttpClientFactory",
      "com.alibaba.nacos.client.env.convert.CompositeConverter",
      "com.alibaba.nacos.common.http.client.response.JdkHttpClientResponse",
      "com.alibaba.nacos.common.executor.NameThreadFactory",
      "com.alibaba.nacos.client.env.SystemEnvPropertySource",
      "com.alibaba.nacos.common.utils.ResourceUtils",
      "com.alibaba.nacos.common.http.HttpClientConfig",
      "com.alibaba.nacos.plugin.auth.api.RequestResource",
      "com.alibaba.nacos.client.env.SearchableProperties",
      "com.alibaba.nacos.plugin.auth.api.LoginIdentityContext",
      "com.alibaba.nacos.api.exception.NacosException",
      "com.alibaba.nacos.api.naming.pojo.ServiceInfo",
      "com.alibaba.nacos.plugin.auth.api.RequestResource$Builder",
      "com.alibaba.nacos.client.naming.remote.gprc.redo.NamingGrpcRedoService",
      "com.alibaba.nacos.api.naming.remote.request.ServiceQueryRequest",
      "com.alibaba.nacos.common.spi.ServiceLoaderException",
      "com.alibaba.nacos.common.http.client.handler.BeanResponseHandler",
      "com.alibaba.nacos.api.naming.remote.request.BatchInstanceRequest",
      "com.alibaba.nacos.client.env.JvmArgsPropertySource",
      "com.alibaba.nacos.common.notify.SlowEvent",
      "com.alibaba.nacos.common.http.HttpRestResult"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(NamingGrpcRedoService_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "com.alibaba.nacos.client.naming.remote.gprc.redo.NamingGrpcRedoService",
      "com.alibaba.nacos.client.logging.NacosLogging",
      "com.alibaba.nacos.client.env.AbstractPropertySource",
      "com.alibaba.nacos.client.env.JvmArgsPropertySource",
      "com.alibaba.nacos.client.env.SystemEnvPropertySource",
      "com.alibaba.nacos.client.env.DefaultSettingPropertySource",
      "com.alibaba.nacos.common.utils.ResourceUtils",
      "com.alibaba.nacos.client.env.SourceType",
      "com.alibaba.nacos.client.env.convert.CompositeConverter",
      "com.alibaba.nacos.client.env.convert.AbstractPropertyConverter",
      "com.alibaba.nacos.client.env.convert.BooleanConverter",
      "com.alibaba.nacos.client.env.convert.IntegerConverter",
      "com.alibaba.nacos.client.env.convert.LongConverter",
      "com.alibaba.nacos.client.env.PropertiesPropertySource",
      "com.alibaba.nacos.common.utils.StringUtils",
      "com.alibaba.nacos.client.env.SearchableProperties",
      "com.alibaba.nacos.client.env.NacosClientProperties",
      "com.alibaba.nacos.client.logging.AbstractNacosLogging",
      "com.alibaba.nacos.client.logging.logback.LogbackNacosLogging",
      "com.alibaba.nacos.client.logging.NacosLogging$NacosLoggingInstance",
      "com.alibaba.nacos.client.logging.logback.NacosJoranConfigurator",
      "com.alibaba.nacos.client.utils.LogUtils",
      "com.alibaba.nacos.client.naming.core.ServerListManager",
      "com.alibaba.nacos.client.naming.remote.http.NamingHttpClientManager",
      "com.alibaba.nacos.common.executor.NameThreadFactory",
      "com.alibaba.nacos.common.task.AbstractExecuteTask",
      "com.alibaba.nacos.client.naming.remote.gprc.redo.RedoScheduledTask",
      "com.alibaba.nacos.api.naming.utils.NamingUtils",
      "com.alibaba.nacos.api.utils.StringUtils",
      "com.alibaba.nacos.api.naming.pojo.ServiceInfo",
      "com.alibaba.nacos.common.http.param.Header",
      "com.alibaba.nacos.common.http.client.AbstractNacosRestTemplate",
      "com.alibaba.nacos.common.http.client.NacosRestTemplate",
      "com.alibaba.nacos.common.http.client.handler.AbstractResponseHandler",
      "com.alibaba.nacos.common.http.client.handler.StringResponseHandler",
      "com.alibaba.nacos.common.http.client.handler.RestResultResponseHandler",
      "com.alibaba.nacos.common.http.client.handler.BeanResponseHandler",
      "com.alibaba.nacos.client.security.SecurityProxy",
      "com.alibaba.nacos.plugin.auth.spi.client.ClientAuthPluginManager",
      "com.alibaba.nacos.common.spi.NacosServiceLoader",
      "com.alibaba.nacos.plugin.auth.spi.client.AbstractClientAuthService",
      "com.alibaba.nacos.client.auth.impl.NacosClientAuthServiceImpl",
      "com.alibaba.nacos.plugin.auth.api.LoginIdentityContext",
      "com.alibaba.nacos.client.auth.ram.RamClientAuthServiceImpl",
      "com.alibaba.nacos.client.auth.ram.RamContext",
      "com.alibaba.nacos.client.auth.ram.injector.AbstractResourceInjector",
      "com.alibaba.nacos.client.auth.ram.injector.NamingResourceInjector",
      "com.alibaba.nacos.common.http.client.request.JdkHttpClientRequest",
      "com.alibaba.nacos.common.http.HttpClientConfig",
      "com.alibaba.nacos.client.naming.cache.ServiceInfoHolder",
      "com.alibaba.nacos.client.naming.backups.FailoverReactor",
      "com.alibaba.nacos.client.naming.backups.FailoverReactor$SwitchRefresher",
      "com.alibaba.nacos.client.naming.backups.FailoverReactor$DiskFileWriter",
      "com.alibaba.nacos.plugin.auth.api.RequestResource",
      "com.alibaba.nacos.common.notify.listener.Subscriber",
      "com.alibaba.nacos.client.naming.remote.AbstractNamingClientProxy",
      "com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy",
      "com.alibaba.nacos.api.naming.pojo.Instance",
      "com.alibaba.nacos.api.naming.pojo.Service",
      "com.alibaba.nacos.client.naming.remote.gprc.redo.data.RedoData",
      "com.alibaba.nacos.client.naming.remote.gprc.redo.data.InstanceRedoData",
      "com.alibaba.nacos.client.naming.remote.gprc.redo.data.SubscriberRedoData",
      "com.alibaba.nacos.common.http.HttpClientConfig$HttpClientConfigBuilder",
      "com.alibaba.nacos.common.utils.ThreadUtils",
      "com.alibaba.nacos.common.utils.PropertyUtils",
      "com.alibaba.nacos.api.common.Constants",
      "com.alibaba.nacos.plugin.auth.api.RequestResource$Builder",
      "com.alibaba.nacos.client.naming.remote.gprc.redo.data.RedoData$RedoType",
      "com.alibaba.nacos.client.naming.remote.gprc.redo.data.BatchInstanceRedoData",
      "com.alibaba.nacos.common.http.param.Query",
      "com.alibaba.nacos.common.utils.CollectionUtils",
      "com.alibaba.nacos.common.utils.ConvertUtils",
      "com.alibaba.nacos.common.utils.InternetAddressUtil",
      "com.alibaba.nacos.common.tls.SelfHostnameVerifier",
      "com.alibaba.nacos.common.http.client.response.JdkHttpClientResponse",
      "com.alibaba.nacos.common.model.RequestHttpEntity",
      "com.alibaba.nacos.common.utils.MapUtil"
    );
  }
}
